cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name="cart_detail"),
    path('add/<int:product_id>', views.cart_add_item, name="cart_add"),
    path('remove/<int:product_id>', views.cart_remove_item, name='cart_remove'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace="shop")),
    path('cart/', include('cart.urls', namespace='cart')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import ProductList, ProductDetail

app_name = 'shop'

urlpatterns = [
    path('', ProductList.as_view(), name='product-list'),
    path('<slug:category_slug>', ProductList.as_view(), name='product-list-by-cat'),
    path('<int:pk>/<slug:slug>', ProductDetail.as_view(), name='product-detail'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name', ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:product-list-by-cat', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    description = models.TextField(blank=True)

    price = models.DecimalField(max_digits=10, decimal_places=2)

    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return reverse('shop:product-detail', args=[self.id, self.slug])

    def __str__(self):
        return self.name

cart/forms.py
from django import forms

PRODUCT_QTY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddItemForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QTY_CHOICES, coerce=int)
    update_qty = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView
from .cart import Cart
from .forms import CartAddItemForm
from shop.models import Product


@require_POST
def cart_add_item(request, product_id):

    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_id)

    add_item_form =  CartAddItemForm(request.POST)

    if add_item_form.is_valid():
        
        form_data = add_item_form.cleaned_data

        cart.add(product, form_data['quantity'], form_data['update_qty'])

        return redirect('cart:cart_detail')


def cart_remove_item(request, product_id):
    
    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_id)    

    cart.remove(product)

    return redirect('cart:cart_detail')


class CartDetailView(TemplateView):
    template_name = 'cart/cart_detail.html'

    def get_context_data(self, **kwargs):

        ctx = super().get_context_data(**kwargs)

        cart = Cart(self.request)

        ctx['cart'] = cart

        return ctx

shop/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Product, Category
from cart.forms import CartAddItemForm


class ProductList(ListView):
    queryset = Product.objects.filter(available=True)
    
    context_object_name = 'products'

    def get_queryset(self):

        qs = super().get_queryset()

        if 'category_slug' in self.kwargs:
            category = get_object_or_404(Category,
                                         slug=self.kwargs.get('category_slug'))

            qs = qs.filter(category=category)

        return qs

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        ctx["categories"] = Category.objects.all()

        return ctx


class ProductDetail(DetailView):
    queryset = Product.objects.filter(available=True)
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):

        ctx = super().get_context_data(**kwargs)

        ctx["cart_product_form"] = CartAddItemForm()

        return ctx

cart/templates/cart/cart_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}
    {% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>
                    <a href="{% url "cart:cart_remove" product.id%}">Remove</a>
                </td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price }}</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product-list" %}" class="button
    light">Continue shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <title>
        {% block title %}My Shop{% endblock %}
    </title>
</head>

<body>
    <div id="header">
        <a href="/" class="logo">My shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
            Your cart is empty.
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

shop/templates/shop/product_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2>
            <a href="{{ product.category.get_absolute_url }}">
                {{product.category }}
            </a>
        </h2>
        <p class="price">${{ product.price }}</p>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

shop/templates/shop/product_list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Products
    {% endif %}
{% endblock title %}

{% block content %}
<div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url "shop:product-list" %}">All</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>
        {% if category %}
            {{ category.name }}
        {% else %}Products
        {% endif %}
    </h1>
    {% for product in products %}
    {% static "img/no_image.png" as no_image %}
        <div class="item">
            <a href="{{ product.get_absolute_url }}">
                {% if product.image %}
                    <img src="{{ product.image.url }}">
                {%else %}
                <img src="{{ no_image }}">    
                {% endif %}
            </a>
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
            <br>
            ${{ product.price }}
        </div>
    {% endfor %}
</div>
{% endblock %}